import assert from 'node:assert/strict'
import fs from 'node:fs'
const sql = fs.readFileSync('supabase/migrations/009_phase3_lifecycle.sql','utf8')
const voidRoute = fs.readFileSync('src/app/api/records/void/route.ts','utf8')
const paymentRoute = fs.readFileSync('src/app/api/payments/route.ts','utf8')
const bankRoute = fs.readFileSync('src/app/api/bank/import/route.ts','utf8')
const evidenceRoute = fs.readFileSync('src/app/api/evidence/route.ts','utf8')
assert.match(sql, /CREATE OR REPLACE FUNCTION public\.post_payment_transaction/)
assert.match(sql, /CREATE OR REPLACE FUNCTION public\.void_record_transaction/)
assert.match(sql, /Allocation exceeds available payment or invoice balance/)
assert.match(sql, /row_fingerprint TEXT/)
assert.match(sql, /sha256_hash TEXT/)
assert.match(voidRoute, /void_record_transaction/)
assert.doesNotMatch(voidRoute, /\.update\(\{ status: 'void' \}\)/)
assert.match(paymentRoute, /post_payment_transaction/)
assert.match(bankRoute, /row_fingerprint/)
assert.match(bankRoute, /ignoreDuplicates: true/)
assert.match(evidenceRoute, /sha256_hash: hash/)
console.log('phase 3 lifecycle checks passed')
